_wandb:
    value:
        cli_version: 0.21.0
        e:
            cyl0yzqxdchwjxkb51gpz4v7yqgeilvv:
                args:
                    - --weights
                    - yolo11s.pt
                    - --data
                    - configs/yolo_data.yaml
                    - --cfg
                    - configs/yolo_hyp_small_objects.yaml
                    - --imgsz
                    - "960"
                    - --epochs
                    - "200"
                    - --batch
                    - "32"
                    - --project
                    - runs/train_smallobj_dryrun
                    - --name-suffix
                    - smoke
                codePath: train_yolo.py
                codePathLocal: train_yolo.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "8656922775552"
                        used: "7049922772992"
                email: nguyenanhkhoi0608@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 43d706592849a9367552a9b4b4bc214efe22eae4
                    remote: https://TheMetaSetter:@github.com/TheMetaSetter/cvweare_zaic2025.git
                gpu: Tesla T4
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-50b722fd-fb11-1538-a75d-5c6de11b7089
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-0ddf286d-2a07-e22d-cdf4-c9c5240a7965
                host: 69d049cbf127
                memory:
                    total: "33662320640"
                os: Linux-6.6.56+-x86_64-with-glibc2.35
                program: /kaggle/working/cvweare_zaic2025/train_yolo.py
                python: CPython 3.11.13
                root: /kaggle/working/cvweare_zaic2025
                startedAt: "2025-11-19T16:25:27.046460Z"
                writerId: cyl0yzqxdchwjxkb51gpz4v7yqgeilvv
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 30
                - 105
            "2":
                - 1
                - 30
                - 41
                - 49
                - 80
                - 105
            "3":
                - 13
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "8":
                - 2
            "12": 0.21.0
            "13": linux-x86_64
agnostic_nms:
    value: false
amp:
    value: true
augment:
    value: false
auto_augment:
    value: randaugment
batch:
    value: 32
bgr:
    value: 0
box:
    value: 7.5
cache:
    value: false
cfg:
    value: configs/yolo_hyp_small_objects.yaml
classes:
    value: null
close_mosaic:
    value: 20
cls:
    value: 0.4
compile:
    value: false
conf:
    value: null
copy_paste:
    value: 0
copy_paste_mode:
    value: flip
cos_lr:
    value: false
cutmix:
    value: 0
data:
    value: configs/yolo_data.yaml
degrees:
    value: 5
deterministic:
    value: true
device:
    value: "0"
dfl:
    value: 1.5
dnn:
    value: false
dropout:
    value: 0
dynamic:
    value: false
embed:
    value: null
epochs:
    value: 200
erasing:
    value: 0.4
exist_ok:
    value: false
fliplr:
    value: 0.5
flipud:
    value: 0
format:
    value: torchscript
fraction:
    value: 1
freeze:
    value: null
half:
    value: false
hsv_h:
    value: 0.015
hsv_s:
    value: 0.5
hsv_v:
    value: 0.4
imgsz:
    value: 960
int8:
    value: false
iou:
    value: 0.7
keras:
    value: false
kobj:
    value: 1
line_width:
    value: null
lr0:
    value: 0.005
lrf:
    value: 0.003
mask_ratio:
    value: 4
max_det:
    value: 300
mixup:
    value: 0.05
mode:
    value: train
model:
    value: yolo11s.pt
momentum:
    value: 0.937
mosaic:
    value: 0.5
multi_scale:
    value: false
name:
    value: yolo11s_smoke
nbs:
    value: 64
nms:
    value: false
opset:
    value: null
optimize:
    value: false
optimizer:
    value: auto
overlap_mask:
    value: true
patience:
    value: 50
perspective:
    value: 0
plots:
    value: true
pose:
    value: 12
pretrained:
    value: true
profile:
    value: false
project:
    value: runs/train_smallobj_dryrun
rect:
    value: false
resume:
    value: false
retina_masks:
    value: false
save:
    value: true
save_conf:
    value: false
save_crop:
    value: false
save_dir:
    value: /kaggle/working/cvweare_zaic2025/runs/train_smallobj_dryrun/yolo11s_smoke
save_frames:
    value: false
save_json:
    value: false
save_period:
    value: -1
save_txt:
    value: false
scale:
    value: 0.4
seed:
    value: 0
shear:
    value: 1
show:
    value: false
show_boxes:
    value: true
show_conf:
    value: true
show_labels:
    value: true
simplify:
    value: true
single_cls:
    value: false
source:
    value: null
split:
    value: val
stream_buffer:
    value: false
task:
    value: detect
time:
    value: null
tracker:
    value: botsort.yaml
translate:
    value: 0.08
val:
    value: true
verbose:
    value: true
vid_stride:
    value: 1
visualize:
    value: false
warmup_bias_lr:
    value: 0.05
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.8
weight_decay:
    value: 5e-05
workers:
    value: 8
workspace:
    value: null
