_wandb:
    value:
        cli_version: 0.23.0
        e:
            r5ia38q4sp1p255mvugz2yf655cw4d3y:
                args:
                    - --weights
                    - yolo11n.pt
                    - --data
                    - configs/yolo_data.yaml
                    - --cfg
                    - configs/yolo_hyp_small_objects.yaml
                    - --imgsz
                    - "960"
                    - --epochs
                    - "1"
                    - --batch
                    - "32"
                    - --device
                    - "0"
                    - --project
                    - runs/train_smallobj_dryrun
                    - --name-suffix
                    - smoke
                codePath: train_yolo.py
                codePathLocal: train_yolo.py
                cpu_count: 12
                cpu_count_logical: 12
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "316933189632"
                        used: "55562944512"
                email: nguyenanhkhoi0608@gmail.com
                executable: /root/cvweare_zaic2025/zaic2025/bin/python
                git:
                    commit: 7ac987b27bcf76737320b68ec178e51e8109f3bd
                    remote: https://github.com/TheMetaSetter/cvweare_zaic2025.git
                gpu: NVIDIA RTX A4000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-22cfa26a-a134-1815-f238-584fced79db0
                host: zaic2025cvweare
                memory:
                    total: "49301430272"
                os: Linux-5.15.0-43-generic-x86_64-with-glibc2.35
                program: /root/cvweare_zaic2025/train_yolo.py
                python: CPython 3.10.12
                root: /root/cvweare_zaic2025
                startedAt: "2025-11-18T14:28:16.643193Z"
                writerId: r5ia38q4sp1p255mvugz2yf655cw4d3y
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.12
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
        visualize:
            curves/F1-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: F1-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: F1
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/F1-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Precision-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Precision-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Precision-Recall(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Recall(B)
                        x-axis-title: Recall
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Precision-Recall(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            curves/Recall-Confidence(B):
                panel_config:
                    fieldSettings:
                        class: class
                        x: x
                        "y": "y"
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Recall-Confidence(B)
                        x-axis-title: Confidence
                        y-axis-title: Recall
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: curves/Recall-Confidence(B)_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
agnostic_nms:
    value: false
amp:
    value: true
augment:
    value: false
auto_augment:
    value: randaugment
batch:
    value: 32
bgr:
    value: 0
box:
    value: 7.5
cache:
    value: false
cfg:
    value: configs/yolo_hyp_small_objects.yaml
classes:
    value: null
close_mosaic:
    value: 20
cls:
    value: 0.4
compile:
    value: false
conf:
    value: null
copy_paste:
    value: 0
copy_paste_mode:
    value: flip
cos_lr:
    value: false
cutmix:
    value: 0
data:
    value: configs/yolo_data.yaml
degrees:
    value: 5
deterministic:
    value: true
device:
    value: "0"
dfl:
    value: 1.5
dnn:
    value: false
dropout:
    value: 0
dynamic:
    value: false
embed:
    value: null
epochs:
    value: 1
erasing:
    value: 0.4
exist_ok:
    value: false
fliplr:
    value: 0.5
flipud:
    value: 0
format:
    value: torchscript
fraction:
    value: 1
freeze:
    value: null
half:
    value: false
hsv_h:
    value: 0.015
hsv_s:
    value: 0.5
hsv_v:
    value: 0.4
imgsz:
    value: 960
int8:
    value: false
iou:
    value: 0.7
keras:
    value: false
kobj:
    value: 1
line_width:
    value: null
lr0:
    value: 0.003
lrf:
    value: 0.01
mask_ratio:
    value: 4
max_det:
    value: 300
mixup:
    value: 0.05
mode:
    value: train
model:
    value: yolo11n.pt
momentum:
    value: 0.937
mosaic:
    value: 0.5
multi_scale:
    value: false
name:
    value: yolo11n_smoke2
nbs:
    value: 64
nms:
    value: false
opset:
    value: null
optimize:
    value: false
optimizer:
    value: auto
overlap_mask:
    value: true
patience:
    value: 50
perspective:
    value: 0
plots:
    value: true
pose:
    value: 12
pretrained:
    value: true
profile:
    value: false
project:
    value: runs/train_smallobj_dryrun
rect:
    value: false
resume:
    value: false
retina_masks:
    value: false
save:
    value: true
save_conf:
    value: false
save_crop:
    value: false
save_dir:
    value: /root/cvweare_zaic2025/runs/train_smallobj_dryrun/yolo11n_smoke2
save_frames:
    value: false
save_json:
    value: false
save_period:
    value: -1
save_txt:
    value: false
scale:
    value: 0.4
seed:
    value: 0
shear:
    value: 1
show:
    value: false
show_boxes:
    value: true
show_conf:
    value: true
show_labels:
    value: true
simplify:
    value: true
single_cls:
    value: false
source:
    value: null
split:
    value: val
stream_buffer:
    value: false
task:
    value: detect
time:
    value: null
tracker:
    value: botsort.yaml
translate:
    value: 0.08
val:
    value: true
verbose:
    value: true
vid_stride:
    value: 1
visualize:
    value: false
warmup_bias_lr:
    value: 0.05
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.8
weight_decay:
    value: 0.0005
workers:
    value: 8
workspace:
    value: null
